# states to download and process stats
states = [
     'NY',
     'OK',
     'MT',
     'MA',
     'NM',
     'WY',
     'OH',
     'MS',
     'NH',
     'MD',
     'CO',
     'UT',
     'ME',
     'LA',
     'PRUSVI',
     'MP',
     'AS',
     'WI',
     'AR',
     'NJ',
     'GU',
     'GA',
     'SD',
     'IN',
     'KS',
     'IL',
     'SC',
     'HI',
     'IA',
     'FL',
     'PA',
     'RI',
     'PW',
     'FM',
     'DE',
     'KY',
     'DC',
     'ID',
     'VA',
     'CA',
     'ND',
     'MH',
     'AK',
     'CT',
     'VT',
     'MI',
     'NE',
     'NV',
     'OR',
     'TX',
     'TN',
     'MN',
     'AZ',
     'WA',
     'WV',
     'AL',
     'NC',
     'MO',
         ]


# tables that will be processed for stats
dct = {
    'mapunit': {
        'musym': 'str',
        'muname': 'str',
        'mukind': 'str',
        'mustatus': 'str',
        'muacres': 'int',
        'mapunitlfw_l': 'int',
        'mapunitlfw_r': 'int',
        'mapunitlfw_h': 'int',
        'mapunitpfa_l': 'float',
        'mapunitpfa_r': 'float',
        'mapunitpfa_h': 'float',
        'farmlndcl': 'str',
        'muhelcl': 'str',
        'muwathelcl': 'str',
        'muwndhelcl': 'str',
        'interpfocus': 'str',
        'invesintens': 'str',
        'iacornsr': 'int',
        'nhiforsoigrp': 'str',
        'nhspiagr': 'float',
        'vtsepticsyscl': 'str',
        'mucertstat': 'str',
        'lkey': 'str',
        'mukey': 'str',
    },

    'component': {
        'comppct_l': 'int',
        'comppct_r': 'int',
        'comppct_h': 'int',
        'compname': 'str',
        'compkind': 'str',
        'majcompflag': 'str',
        'otherph': 'str',
        'localphase': 'str',
        'slope_l': 'float',
        'slope_r': 'float',
        'slope_h': 'float',
        'slopelenusle_l': 'int',
        'slopelenusle_r': 'int',
        'slopelenusle_h': 'int',
        'runoff': 'str',
        'tfact': 'int',
        'wei': 'str',
        'weg': 'str',
        'erocl': 'str',
        'earthcovkind1': 'str',
        'earthcovkind2': 'str',
        'hydricon': 'str',
        'hydricrating': 'str',
        'drainagecl': 'str',
        'elev_l': 'float',
        'elev_r': 'float',
        'elev_h': 'float',
        'aspectccwise': 'int',
        'aspectrep': 'int',
        'aspectcwise': 'int',
        'geomdesc': 'str',
        'albedodry_l': 'float',
        'albedodry_r': 'float',
        'albedodry_h': 'float',
        'airtempa_l': 'float',
        'airtempa_r': 'float',
        'airtempa_h': 'float',
        'map_l': 'int',
        'map_r': 'int',
        'map_h': 'int',
        'reannualprecip_l': 'int',
        'reannualprecip_r': 'int',
        'reannualprecip_h': 'int',
        'ffd_l': 'int',
        'ffd_r': 'int',
        'ffd_h': 'int',
        'nirrcapcl': 'str',
        'nirrcapscl': 'str',
        'nirrcapunit': 'int',
        'irrcapcl': 'str',
        'irrcapscl': 'str',
        'irrcapunit': 'int',
        'cropprodindex': 'int',
        'constreeshrubgrp': 'str',
        'wndbrksuitgrp': 'str',
        'rsprod_l': 'int',
        'rsprod_r': 'int',
        'rsprod_h': 'int',
        'foragesuitgrpid': 'str',
        'wlgrain': 'str',
        'wlgrass': 'str',
        'wlherbaceous': 'str',
        'wlshrub': 'str',
        'wlconiferous': 'str',
        'wlhardwood': 'str',
        'wlwetplant': 'str',
        'wlshallowwat': 'str',
        'wlrangeland': 'str',
        'wlopenland': 'str',
        'wlwoodland': 'str',
        'wlwetland': 'str',
        'soilslippot': 'str',
        'frostact': 'str',
        'initsub_l': 'int',
        'initsub_r': 'int',
        'initsub_h': 'int',
        'totalsub_l': 'int',
        'totalsub_r': 'int',
        'totalsub_h': 'int',
        'hydgrp': 'str',
        'corcon': 'str',
        'corsteel': 'str',
        'taxclname': 'str',
        'taxorder': 'str',
        'taxsuborder': 'str',
        'taxgrtgroup': 'str',
        'taxsubgrp': 'str',
        'taxpartsize': 'str',
        'taxpartsizemod': 'str',
        'taxceactcl': 'str',
        'taxreaction': 'str',
        'taxtempcl': 'str',
        'taxmoistscl': 'str',
        'taxtempregime': 'str',
        'soiltaxedition': 'str',
        'castorieindex': 'int',
        'flecolcomnum': 'str',
        'flhe': 'str',
        'flphe': 'str',
        'flsoilleachpot': 'str',
        'flsoirunoffpot': 'str',
        'fltemik2use': 'str',
        'fltriumph2use': 'str',
        'indraingrp': 'str',
        'innitrateleachi': 'int',
        'misoimgmtgrp': 'str',
        'vasoimgtgrp': 'str',
        'mukey': 'str',
        'cokey': 'str',
    },

    'muaggatt': {
        'musym': 'str',
        'muname': 'str',
        'mustatus': 'str',
        'slopegraddcp': 'float',
        'slopegradwta': 'float',
        'brockdepmin': 'int',
        'wtdepannmin': 'int',
        'wtdepaprjunmin': 'int',
        'flodfreqdcd': 'str',
        'flodfreqmax': 'str',
        'pondfreqprs': 'str',
        'aws025wta': 'float',
        'aws050wta': 'float',
        'aws0100wta': 'float',
        'aws0150wta': 'float',
        'drclassdcd': 'str',
        'drclasswettest': 'str',
        'hydgrpdcd': 'str',
        'iccdcd': 'str',
        'iccdcdpct': 'int',
        'niccdcd': 'str',
        'niccdcdpct': 'int',
        'engdwobdcd': 'str',
        'engdwbdcd': 'str',
        'engdwbll': 'str',
        'engdwbml': 'str',
        'engstafdcd': 'str',
        'engstafll': 'str',
        'engstafml': 'str',
        'engsldcd': 'str',
        'engsldcp': 'str',
        'englrsdcd': 'str',
        'engcmssdcd': 'str',
        'engcmssmp': 'str',
        'urbrecptdcd': 'str',
        'urbrecptwta': 'float',
        'forpehrtdcp': 'str',
        'hydclprs': 'str',
        'awmmfpwwta': 'float',
        'mukey': 'str',

    },

    'mucropyld': {
        'cropname': 'str',
        'yldunits': 'str',
        'nonirryield_l': 'float',
        'nonirryield_r': 'float',
        'nonirryield_h': 'float',
        'irryield_l': 'float',
        'irryield_r': 'float',
        'irryield_h': 'float',
        'mukey': 'str',
        'mucrpyldkey': 'str',
    },

    'valu1': {
        'aws0_5': 'float',
        'aws5_20': 'float',
        'aws20_50': 'float',
        'aws50_100': 'float',
        'aws100_150': 'float',
        'aws150_999': 'float',
        'aws0_20': 'float',
        'aws0_30': 'float',
        'aws0_100': 'float',
        'aws0_150': 'float',
        'aws0_999': 'float',
        'tk0_5a': 'float',
        'tk5_20a': 'float',
        'tk20_50a': 'float',
        'tk50_100a': 'float',
        'tk100_150a': 'float',
        'tk150_999a': 'float',
        'tk0_20a': 'float',
        'tk0_30a': 'float',
        'tk0_100a': 'float',
        'tk0_150a': 'float',
        'tk0_999a': 'float',
        'musumcpcta': 'int',
        'soc0_5': 'float',
        'soc5_20': 'float',
        'soc20_50': 'float',
        'soc50_100': 'float',
        'soc100_150': 'float',
        'soc150_999': 'float',
        'soc0_20': 'float',
        'soc0_30': 'float',
        'soc0_100': 'float',
        'soc0_150': 'float',
        'soc0_999': 'float',
        'tk0_5s': 'float',
        'tk5_20s': 'float',
        'tk20_50s': 'float',
        'tk50_100s': 'float',
        'tk100_150s': 'float',
        'tk150_999s': 'float',
        'tk0_20s': 'float',
        'tk0_30s': 'float',
        'tk0_100s': 'float',
        'tk0_150s': 'float',
        'tk0_999s': 'float',
        'musumcpcts': 'int',
        'nccpi3corn': 'float',
        'nccpi3soy': 'float',
        'nccpi3cot': 'float',
        'nccpi3sg': 'float',
        'nccpi3all': 'float',
        'pctearthmc': 'int',
        'rootznemc': 'int',
        'rootznaws': 'int',
        'droughty': 'int',
        'pwsl1pomu': 'int',
        'musumcpct': 'int',
        'mukey': 'str',
    },
}
